import pandas as pd
import matplotlib.pyplot as plt
import json
import sys
sys.path.append('../')


dataFile = ""
# imort rawDataFile from config
with open ('config.json') as config_file:
    config = json.load(config_file)

if config and config.get('rawDataFile'):
    dataFile = config.get('rawDataFile')
else:
    print('Error: config file is missing or invalid')
    sys.exit(1)

# Load the data from the CSV file
data = pd.read_csv(dataFile)

# Create a box plot of reading score by parental level of education
data.boxplot(column='reading score', by='parental level of education', figsize=(10, 6))
plt.title('Reading Score by Parental Level of Education')
plt.suptitle('')  # Remove the default title generated by pandas
plt.xlabel('Parental Level of Education')
plt.ylabel('Reading Score')
plt.show()
plt.savefig('figures/BoxParentalLevelOfEducationReading.png')
