#!/usr/bin/env python
# coding: utf-8

# In[4]:


import pandas as pd
import matplotlib.pyplot as plt
import json
import seaborn as sns


# In[2]:


import sys
sys.path.append('../')


# In[7]:


data = pd.read_csv("C:/Users/Administrator/Desktop/data science/StudentsPerformance.csv")


# In[8]:


# Calculate the average math score for each race
avg_math_by_race = data.groupby('race/ethnicity')['math score'].mean()


# In[10]:


# Create a bar chart of the average math score by race
plt.bar(avg_math_by_race.index, avg_math_by_race)
plt.title('Average Math Score vs Race')
plt.xlabel('Race')
plt.ylabel('Average Math Score')
plt.show()
# Observation :The average Math Score of Group E students is highest among all the groups


# In[11]:


# Create a box plot of reading score by parental level of education
data.boxplot(column='reading score', by='parental level of education', figsize=(10, 6))
plt.title('Reading Score vs Parental Level of Education')
plt.suptitle('')  # Remove the default title generated by pandas
plt.xlabel('Parental Level of Education')
plt.ylabel('Reading Score')
plt.show()
# Observation :The Reading Score of the student doesn't depend upon the  Parental Level of Education


# In[11]:


# Calculate the average scores by race and gender
avg_scores = data.groupby(['race/ethnicity', 'gender'])[['math score', 'reading score', 'writing score']].mean()


# In[14]:


# Create a heatmap of the average scores
sns.heatmap(avg_scores, annot=True, cmap='coolwarm', fmt='.1f')
plt.title('Average Scores by Race and Gender')
plt.show()
# Observation:The average Math Score is highest in Group E male and Group E female scored highest in Reading and Writing


# In[15]:


# Create a scatter plot of math score versus reading score
plt.scatter(data['math score'], data['reading score'])
plt.title('Math Score vs Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()
# The student who scored good in maths has scored good in Reading also,The divergence of maths score and reading score is not huge 


# In[16]:


math_counts = data.groupby(['gender', pd.cut(data['math score'], bins=[0, 40, 60, 80, 100])]).size().unstack()
reading_counts = data.groupby(['gender', pd.cut(data['reading score'], bins=[0, 40, 60, 80, 100])]).size().unstack()
writing_counts = data.groupby(['gender', pd.cut(data['writing score'], bins=[0, 40, 60, 80, 100])]).size().unstack()


# In[17]:


fig, axs = plt.subplots(3, 1, figsize=(8, 12))
math_counts.plot(kind='bar', stacked=True, ax=axs[0])
reading_counts.plot(kind='bar', stacked=True, ax=axs[1])
writing_counts.plot(kind='bar', stacked=True, ax=axs[2])
plt.tight_layout()
plt.show()

#Most number of students(both male and Female) has Scored between 60-80 in Maths,Reading,Writing


# In[ ]:




